### ISSUE TITLE
Model weights available?

### ISSUE THREAD

**Issue by johnny0213** [CogStack/OpenGPT#2]
Thanks for your brilliant work! I'm wondering if the model weights are available for us to download. Cheers.

**Comment by w-is-h** [comment]
hi @johnny0213, the current model is LLaMA based so we cannot share the weights (Meta does not allow that). But, we are training other (open source) models and will share once ready.

**Comment by teknium1** [comment]
> hi @johnny0213, the current model is LLaMA based so we cannot share the weights (Meta does not allow that). But, we are training other (open source) models and will share once ready.

I'd recommend MPT :]
